seed: 42
fs_target: 100        # resampling Ä¯ 100 Hz
epoch_sec: 30
channel: "Fpz-Cz"
classes: ["W", "N1", "N2", "N3", "REM"]

paths:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  models_dir: "models"
  results_dir: "results"

split:
  strategy: "by_subject"
  val_subjects:  ["SC4081E0","SC4082E0","SC4091E0","SC4092E0","SC4101E0"]
  test_subjects: ["SC4102E0","SC4111E0","SC4112E0","SC4121E0","SC4122E0"]
